/Library/Frameworks/Python.framework/Versions/3.12/bin/python3 /Users/vuppupra/src/datapipeline.metadata-lineage/test/python_oracle_jdbc.py 
Traceback (most recent call last):
  File "org.jpype.manager.TypeManager.java", line -1, in org.jpype.manager.TypeManager.findClassByName
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vuppupra/src/datapipeline.metadata-lineage/test/python_oracle_jdbc.py", line 52, in <module>
    connection = connect_to_oracle(username, password, hostname, port, service_name, jar_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vuppupra/src/datapipeline.metadata-lineage/test/python_oracle_jdbc.py", line 13, in connect_to_oracle
    connection = jaydebeapi.connect(
                 ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jaydebeapi/__init__.py", line 412, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jaydebeapi/__init__.py", line 221, in _jdbc_connect_jpype
    jpype.JClass(jclassname)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jpype/_jclass.py", line 99, in __new__
    return _jpype._getClass(jc)
           ^^^^^^^^^^^^^^^^^^^^
java.lang.java.lang.UnsupportedClassVersionError: java.lang.UnsupportedClassVersionError: oracle/jdbc/driver/OracleDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Process finished with exit code 1
